Adding MIDI note QueueItem type and handler
notlion/Cinder-PureDataNode pull request #5
Opened 2017-01-06 23:05 UTC by quilime

Adding a Midi Note QueueItem and enabling the task queue to handle and send MIDI notes.

2017-01-06 23:33 UTC, notlion requested changes
A couple comments..

2017-01-06 23:33 UTC, notlion commented on src/PureDataNode.h
> +  void sendNoteOn(int port, int pitch, int velocity);
Curious why `port` is used here and `channel` in the `NoteOn` struct. Seems like we should pick one or the other. Channel seems like the MIDI nomenclature.

2017-01-06 23:33 UTC, notlion commented on src/PureDataNode.cpp
> +  queueTask([=](pd::PdBase &pd) { pd.sendNoteOn(port, pitch, velocity); } );
Since you've made a new `QueueItem` type, it should be used here. See how it's done in `sendFloat` etc.

2017-01-06 23:37 UTC, notlion commented
Also I think we should have a receiver for `Note`s in the same way that we have one for bangs/floats/symbols.

2017-01-06 23:49 UTC, quilime commented on src/PureDataNode.h
> +  void sendNoteOn(int port, int pitch, int velocity);
Yes -- It should be channel, not port.

2017-01-07 00:25 UTC, quilime reviewed
Renaming port to channel, and utilizing the QueueItem now.

2017-01-07 00:47 UTC, notlion commented
Alright. After thinking about it a bit more, receiving MIDI notes will take a bit more work, since they usually are not destined for the UI thread like other messages. Let's keep this PR focused on sending MIDI notes.

I think after the port -> channel naming is fixed this can be merged.

2017-01-07 00:48 UTC, notlion commented on src/PureDataNode.cpp
> +  mQueueToAudio.enqueue(QueueItem(Note { channel, pitch, velocity } ));
Curly brace style should be consistent with the rest of the file.

2017-01-07 23:57 UTC, quilime commented
Apologies in advance for the messy, sporadic commits. Definitely rebase/squash when it's done.

2017-01-08 05:26 UTC, quilime reviewed
Added a bunch more types.

2017-01-08 06:51 UTC, notlion approved these changes

2017-01-08 06:53 UTC, merged